module_name: "user"
# NOTICE: localだと、モジュールごとのvar_locationsでは、envが使えない。
# 環境によって、1つしか環境変数は設定できないため。
var_locations: [dotenv]
# ssm_param_paths:
#   "/app_name1/local/service_name1": ["DB_HOST", "DB_PORT", "DB_USER", "DB_PASSWORD", "DB_NAME"]
# secrets_manager_ids: ["test-secret1", "test-secret2"]

